name: build dapp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push

    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      - name: Build
        env:
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_CLIENT_ID_DEV: ${{ secrets.VITE_GOOGLE_CLIENT_ID_DEV }}
          VITE_APPLE_CLIENT_ID: ${{ secrets.VITE_APPLE_CLIENT_ID }}
          VITE_PLAYFAB_TITLE_ID: ${{ secrets.VITE_PLAYFAB_TITLE_ID }}
          VITE_SEQUENCE_PROJECT_ACCESS_KEY: ${{ secrets.VITE_SEQUENCE_PROJECT_ACCESS_KEY }}
          VITE_SEQUENCE_WAAS_CONFIG_KEY: ${{ secrets.VITE_SEQUENCE_WAAS_CONFIG_KEY }}
          VITE_SEQUENCE_PROJECT_ACCESS_KEY_DEV: ${{ secrets.VITE_SEQUENCE_PROJECT_ACCESS_KEY_DEV }}
          VITE_SEQUENCE_WAAS_CONFIG_KEY_DEV: ${{ secrets.VITE_SEQUENCE_WAAS_CONFIG_KEY_DEV }}
          VITE_SEQUENCE_INDEXER_API_KEY: ${{ secrets.VITE_SEQUENCE_INDEXER_API_KEY }}
          VITE_STYTCH_PUBLIC_TOKEN: ${{ secrets.VITE_STYTCH_PUBLIC_TOKEN }}
          VITE_STYTCH_LEGACY_ISSUER: ${{ secrets.VITE_STYTCH_LEGACY_ISSUER }}
        run: pnpm build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}'
